"""make conversions user_id nullable

Revision ID: 583432b6355a
Revises: d95aafebc784
Create Date: 2026-02-01 15:30:02.289190+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '583432b6355a'
down_revision: Union[str, Sequence[str], None] = 'd95aafebc784'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('conversions', 'user_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.drop_index(op.f('ix_conversions_user_id'), table_name='conversions')
    op.create_index(op.f('ix_conversions_user_id'), 'conversions', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_conversions_user_id'), table_name='conversions')
    op.create_index(op.f('ix_conversions_user_id'), 'conversions', ['user_id'], unique=True)
    op.alter_column('conversions', 'user_id',
               existing_type=sa.UUID(),
               nullable=False)
    # ### end Alembic commands ###
