-- Migration: Add missing fields to commissions table
-- Date: 2026-01-31
-- Description: Adds revenue, commission_rate, and updated_at fields to support agent statistics

ALTER TABLE commissions
    -- Rename existing column
    RENAME COLUMN source_user_id TO user_id;

ALTER TABLE commissions
    -- Add revenue tracking
    ADD COLUMN IF NOT EXISTS revenue NUMERIC(18, 2) NOT NULL DEFAULT 0,
    
    -- Add commission rate percentage
    ADD COLUMN IF NOT EXISTS commission_rate NUMERIC(5, 2) NOT NULL DEFAULT 10,
    
    -- Add updated_at timestamp
    ADD COLUMN IF NOT EXISTS updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP;

-- Update existing records with default values
UPDATE commissions
SET 
    revenue = COALESCE(revenue, 0),
    commission_rate = COALESCE(commission_rate, 10),
    updated_at = COALESCE(updated_at, created_at)
WHERE revenue IS NULL OR commission_rate IS NULL OR updated_at IS NULL;

-- Optional: Add index for better query performance
CREATE INDEX IF NOT EXISTS idx_commissions_agent_id ON commissions(agent_id);
CREATE INDEX IF NOT EXISTS idx_commissions_user_id ON commissions(user_id);
CREATE INDEX IF NOT EXISTS idx_commission status ON commissions(status);

COMMENT ON COLUMN commissions.revenue IS 'Total revenue generated by the user';
COMMENT ON COLUMN commissions.commission_rate IS 'Commission rate percentage (e.g., 10 = 10%)';
COMMENT ON COLUMN commissions.user_id IS 'User who generated the revenue (formerly source_user_id)';
