"""add affiliate panel tables and enhancements

Revision ID: d95aafebc784
Revises: 000000000004
Create Date: 2026-02-01 15:05:22.133580+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd95aafebc784'
down_revision: Union[str, Sequence[str], None] = '000000000004'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('affiliate_payouts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('affiliate_id', sa.UUID(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('method', sa.String(), nullable=False),
    sa.Column('destination', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('requested_at', sa.DateTime(), nullable=True),
    sa.Column('processed_at', sa.DateTime(), nullable=True),
    sa.Column('rejection_reason', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['affiliate_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_affiliate_payouts_affiliate_id'), 'affiliate_payouts', ['affiliate_id'], unique=False)
    op.create_index(op.f('ix_affiliate_payouts_requested_at'), 'affiliate_payouts', ['requested_at'], unique=False)
    op.create_index(op.f('ix_affiliate_payouts_status'), 'affiliate_payouts', ['status'], unique=False)
    op.create_table('conversions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('link_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('conversion_type', sa.String(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('commission_earned', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['link_id'], ['affiliate_links.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_conversions_created_at'), 'conversions', ['created_at'], unique=False)
    op.create_index(op.f('ix_conversions_link_id'), 'conversions', ['link_id'], unique=False)
    op.create_index(op.f('ix_conversions_user_id'), 'conversions', ['user_id'], unique=True)
    op.drop_index(op.f('ix_password_reset_tokens_token_hash'), table_name='password_reset_tokens')
    op.drop_table('password_reset_tokens')
    op.add_column('affiliate_links', sa.Column('is_active', sa.Integer(), nullable=True))
    op.alter_column('affiliate_links', 'slug',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('affiliate_links', 'target_url',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.create_index(op.f('ix_affiliate_links_affiliate_id'), 'affiliate_links', ['affiliate_id'], unique=False)
    op.create_index(op.f('ix_affiliate_links_created_at'), 'affiliate_links', ['created_at'], unique=False)
    op.add_column('click_events', sa.Column('user_agent', sa.String(), nullable=True))
    op.add_column('click_events', sa.Column('geo_country', sa.String(), nullable=True))
    op.create_index(op.f('ix_click_events_ip_address'), 'click_events', ['ip_address'], unique=False)
    op.create_index(op.f('ix_click_events_link_id'), 'click_events', ['link_id'], unique=False)
    op.create_index(op.f('ix_click_events_timestamp'), 'click_events', ['timestamp'], unique=False)
    op.drop_column('commissions', 'revenue')
    op.drop_column('commissions', 'commission_rate')
    op.drop_column('commissions', 'updated_at')
    op.drop_constraint(op.f('users_affiliate_link_id_fkey'), 'users', type_='foreignkey')
    op.drop_column('users', 'phone_number')
    op.drop_column('users', 'affiliate_link_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('affiliate_link_id', sa.UUID(), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('phone_number', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('users_affiliate_link_id_fkey'), 'users', 'affiliate_links', ['affiliate_link_id'], ['id'])
    op.add_column('commissions', sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True))
    op.add_column('commissions', sa.Column('commission_rate', sa.NUMERIC(precision=5, scale=2), server_default=sa.text('10'), autoincrement=False, nullable=False))
    op.add_column('commissions', sa.Column('revenue', sa.NUMERIC(precision=18, scale=2), server_default=sa.text('0'), autoincrement=False, nullable=False))
    op.drop_index(op.f('ix_click_events_timestamp'), table_name='click_events')
    op.drop_index(op.f('ix_click_events_link_id'), table_name='click_events')
    op.drop_index(op.f('ix_click_events_ip_address'), table_name='click_events')
    op.drop_column('click_events', 'geo_country')
    op.drop_column('click_events', 'user_agent')
    op.drop_index(op.f('ix_affiliate_links_created_at'), table_name='affiliate_links')
    op.drop_index(op.f('ix_affiliate_links_affiliate_id'), table_name='affiliate_links')
    op.alter_column('affiliate_links', 'target_url',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('affiliate_links', 'slug',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_column('affiliate_links', 'is_active')
    op.create_table('password_reset_tokens',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('token_hash', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('expires_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('is_used', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('password_reset_tokens_user_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('password_reset_tokens_pkey'))
    )
    op.create_index(op.f('ix_password_reset_tokens_token_hash'), 'password_reset_tokens', ['token_hash'], unique=True)
    op.drop_index(op.f('ix_conversions_user_id'), table_name='conversions')
    op.drop_index(op.f('ix_conversions_link_id'), table_name='conversions')
    op.drop_index(op.f('ix_conversions_created_at'), table_name='conversions')
    op.drop_table('conversions')
    op.drop_index(op.f('ix_affiliate_payouts_status'), table_name='affiliate_payouts')
    op.drop_index(op.f('ix_affiliate_payouts_requested_at'), table_name='affiliate_payouts')
    op.drop_index(op.f('ix_affiliate_payouts_affiliate_id'), table_name='affiliate_payouts')
    op.drop_table('affiliate_payouts')
    # ### end Alembic commands ###
