"""add affiliate panel tables and enhancements

Revision ID: d95aafebc784
Revises: 000000000004
Create Date: 2026-02-01 15:05:22.133580+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd95aafebc784'
down_revision: Union[str, Sequence[str], None] = '000000000004'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('affiliate_payouts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('affiliate_id', sa.UUID(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('method', sa.String(), nullable=False),
    sa.Column('destination', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('requested_at', sa.DateTime(), nullable=True),
    sa.Column('processed_at', sa.DateTime(), nullable=True),
    sa.Column('rejection_reason', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['affiliate_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_affiliate_payouts_affiliate_id'), 'affiliate_payouts', ['affiliate_id'], unique=False)
    op.create_index(op.f('ix_affiliate_payouts_requested_at'), 'affiliate_payouts', ['requested_at'], unique=False)
    op.create_index(op.f('ix_affiliate_payouts_status'), 'affiliate_payouts', ['status'], unique=False)
    op.create_table('conversions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('link_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('conversion_type', sa.String(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('commission_earned', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['link_id'], ['affiliate_links.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_conversions_created_at'), 'conversions', ['created_at'], unique=False)
    op.create_index(op.f('ix_conversions_link_id'), 'conversions', ['link_id'], unique=False)
    op.create_index(op.f('ix_conversions_user_id'), 'conversions', ['user_id'], unique=True)
    op.add_column('affiliate_links', sa.Column('is_active', sa.Integer(), nullable=True))
    op.alter_column('affiliate_links', 'slug',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('affiliate_links', 'target_url',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.create_index(op.f('ix_affiliate_links_affiliate_id'), 'affiliate_links', ['affiliate_id'], unique=False)
    op.create_index(op.f('ix_affiliate_links_created_at'), 'affiliate_links', ['created_at'], unique=False)
    op.add_column('click_events', sa.Column('user_agent', sa.String(), nullable=True))
    op.add_column('click_events', sa.Column('geo_country', sa.String(), nullable=True))
    op.create_index(op.f('ix_click_events_ip_address'), 'click_events', ['ip_address'], unique=False)
    op.create_index(op.f('ix_click_events_link_id'), 'click_events', ['link_id'], unique=False)
    op.create_index(op.f('ix_click_events_timestamp'), 'click_events', ['timestamp'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_click_events_timestamp'), table_name='click_events')
    op.drop_index(op.f('ix_click_events_link_id'), table_name='click_events')
    op.drop_index(op.f('ix_click_events_ip_address'), table_name='click_events')
    op.drop_column('click_events', 'geo_country')
    op.drop_column('click_events', 'user_agent')
    op.drop_index(op.f('ix_affiliate_links_created_at'), table_name='affiliate_links')
    op.drop_index(op.f('ix_affiliate_links_affiliate_id'), table_name='affiliate_links')
    op.alter_column('affiliate_links', 'target_url',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('affiliate_links', 'slug',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_column('affiliate_links', 'is_active')
    op.drop_index(op.f('ix_conversions_user_id'), table_name='conversions')
    op.drop_index(op.f('ix_conversions_link_id'), table_name='conversions')
    op.drop_index(op.f('ix_conversions_created_at'), table_name='conversions')
    op.drop_table('conversions')
    op.drop_index(op.f('ix_affiliate_payouts_status'), table_name='affiliate_payouts')
    op.drop_index(op.f('ix_affiliate_payouts_requested_at'), table_name='affiliate_payouts')
    op.drop_index(op.f('ix_affiliate_payouts_affiliate_id'), table_name='affiliate_payouts')
    op.drop_table('affiliate_payouts')
    # ### end Alembic commands ###
