interface CountryCode {
    name: string;
    code: string;
    dial: string;
    flag: string;
}

export const countryCodes: CountryCode[] = [
    { name: "United States", code: "US", dial: "+1", flag: "🇺🇸" },
    { name: "United Kingdom", code: "GB", dial: "+44", flag: "🇬🇧" },
    { name: "Canada", code: "CA", dial: "+1", flag: "🇨🇦" },
    { name: "Australia", code: "AU", dial: "+61", flag: "🇦🇺" },
    { name: "Germany", code: "DE", dial: "+49", flag: "🇩🇪" },
    { name: "France", code: "FR", dial: "+33", flag: "🇫🇷" },
    { name: "Spain", code: "ES", dial: "+34", flag: "🇪🇸" },
    { name: "Italy", code: "IT", dial: "+39", flag: "🇮🇹" },
    { name: "Netherlands", code: "NL", dial: "+31", flag: "🇳🇱" },
    { name: "Belgium", code: "BE", dial: "+32", flag: "🇧🇪" },
    { name: "Switzerland", code: "CH", dial: "+41", flag: "🇨🇭" },
    { name: "Austria", code: "AT", dial: "+43", flag: "🇦🇹" },
    { name: "Sweden", code: "SE", dial: "+46", flag: "🇸🇪" },
    { name: "Norway", code: "NO", dial: "+47", flag: "🇳🇴" },
    { name: "Denmark", code: "DK", dial: "+45", flag: "🇩🇰" },
    { name: "Finland", code: "FI", dial: "+358", flag: "🇫🇮" },
    { name: "Poland", code: "PL", dial: "+48", flag: "🇵🇱" },
    { name: "Czech Republic", code: "CZ", dial: "+420", flag: "🇨🇿" },
    { name: "Portugal", code: "PT", dial: "+351", flag: "🇵🇹" },
    { name: "Greece", code: "GR", dial: "+30", flag: "🇬🇷" },
    { name: "Turkey", code: "TR", dial: "+90", flag: "🇹🇷" },
    { name: "Russia", code: "RU", dial: "+7", flag: "🇷🇺" },
    { name: "Ukraine", code: "UA", dial: "+380", flag: "🇺🇦" },
    { name: "India", code: "IN", dial: "+91", flag: "🇮🇳" },
    { name: "China", code: "CN", dial: "+86", flag: "🇨🇳" },
    { name: "Japan", code: "JP", dial: "+81", flag: "🇯🇵" },
    { name: "South Korea", code: "KR", dial: "+82", flag: "🇰🇷" },
    { name: "Singapore", code: "SG", dial: "+65", flag: "🇸🇬" },
    { name: "Malaysia", code: "MY", dial: "+60", flag: "🇲🇾" },
    { name: "Thailand", code: "TH", dial: "+66", flag: "🇹🇭" },
    { name: "Vietnam", code: "VN", dial: "+84", flag: "🇻🇳" },
    { name: "Philippines", code: "PH", dial: "+63", flag: "🇵🇭" },
    { name: "Indonesia", code: "ID", dial: "+62", flag: "🇮🇩" },
    { name: "Hong Kong", code: "HK", dial: "+852", flag: "🇭🇰" },
    { name: "Taiwan", code: "TW", dial: "+886", flag: "🇹🇼" },
    { name: "United Arab Emirates", code: "AE", dial: "+971", flag: "🇦🇪" },
    { name: "Saudi Arabia", code: "SA", dial: "+966", flag: "🇸🇦" },
    { name: "Qatar", code: "QA", dial: "+974", flag: "🇶🇦" },
    { name: "Kuwait", code: "KW", dial: "+965", flag: "🇰🇼" },
    { name: "Lebanon", code: "LB", dial: "+961", flag: "🇱🇧" },
    { name: "Jordan", code: "JO", dial: "+962", flag: "🇯🇴" },
    { name: "Egypt", code: "EG", dial: "+20", flag: "🇪🇬" },
    { name: "South Africa", code: "ZA", dial: "+27", flag: "🇿🇦" },
    { name: "Nigeria", code: "NG", dial: "+234", flag: "🇳🇬" },
    { name: "Kenya", code: "KE", dial: "+254", flag: "🇰🇪" },
    { name: "Brazil", code: "BR", dial: "+55", flag: "🇧🇷" },
    { name: "Argentina", code: "AR", dial: "+54", flag: "🇦🇷" },
    { name: "Mexico", code: "MX", dial: "+52", flag: "🇲🇽" },
    { name: "Chile", code: "CL", dial: "+56", flag: "🇨🇱" },
    { name: "Colombia", code: "CO", dial: "+57", flag: "🇨🇴" },
    { name: "New Zealand", code: "NZ", dial: "+64", flag: "🇳🇿" },
];
